apiVersion: apps/v1
kind: Deployment
metadata:
  name: abctech-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abctech-1
  template:
    metadata:
      labels:
        app: abctech-1
    spec:
      containers:
      - name: abctech-1
        image: dockerhub696/abctech-1:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: abctech-1-service
spec:
  selector:
    app: abctech-1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
