apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc_tech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abc_tech
  template:
    metadata:
      labels:
        app: abc_tech
    spec:
      containers:
      - name: abc_tech
        image: dockerhub696/abc_tech:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: abc_tech-service
spec:
  selector:
    app: abc_tech
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
