apiVersion: apps/v1
kind: Deployment
metadata:
  name: abctech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abctech
  template:
    metadata:
      labels:
        app: abctech
    spec:
      containers:
      - name: abctech
        image: dockerhub696/abc_tech:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: abctech-service
spec:
  selector:
    app: abctech
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
